name: Experssion.yaml
on: [pull_request, push, issues, workflow_dispatch]
run-name: "experssions and all context by @ ${{github.actor}} , ${{github.event_name}}"

jobs:
  using-experssion-and-context:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: experssion
        run: |
           echo ${{1}}
           echo ${{ 'This is a String '}}
           echo ${{ null }}
           echo ${{ true }}
           echo ${{ 1>2 }}
           echo ${{ true && false }}
           echo ${{ true ||(true && false )}}
      - name: Dump context
        run: |
            echo '${{fromjson(github)}}'
            echo '${{fromjson(job)}}'
            echo '${{fromjson(secrets)}}'
            echo '${{fromjson(steps)}}'
            echo '${{fromjson(runner)}}'


        
