name: Experssion.yaml
on: [pull_request, push, issues, workflow_dispatch]
run-name: "experssions and all context by @ ${{github.actor}} , ${{github.event_name}}"

jobs:
  runs-on-issues-pr:
    runs-on: ubuntu-latest
    if: contains(fromJson('["push","pull_request"]'), github.event_name)  
    steps: 
        - name: Run only if issue has a bug label
          if: contains(fromJson('["issues","pull_request"]'), github.event_name)
          run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}
        - name: Run only if Pull_request has bug label
          if: contains(fromJson('["pull_request"]'), github.event_name)
          run: echo ${{join(github.event.pull_request.labels.*.name, ', ')}}
        
